(async () => {
  const start = Date.now()
  const { LoggerFactory } = require('logger.js')
  const logger = LoggerFactory.getLogger('migrations:makeColumnPersonalPointBoost', 'green')
  const data = require('../src/data')
  process.once('dbready', async () => {
    const expStart = Date.now()
    logger.info('removing personal_expboost column...')
    await data.query('alter table users drop column personal_expboost;')
    const expEnd = Date.now()
    const pointStart = Date.now()
    logger.info('adding personal_pointboost column...')
    await data.query('alter table users add column personal_pointboost;')
    const pointEnd = Date.now()
    logger.info('all done, times:')
      .info(`remove personal_expboost: ${(expEnd-expStart)/1000} seconds`)
      .info(`add personal_pointboost: ${(pointEnd-pointStart)/1000} seconds`)
      .info(`overall: ${(Date.now()-start)/1000} seconds`)
  })
})()
