/**
 * @typedef Tiers
 * @property {{ type: "multiplier" | "expboost" }} tier1
 * @property {{ type: "multiplier" | "expboost" }} tier2
 * @property {{ type: "multiplier" | "expboost" }} tier3
 * @property {{ type: "multiplier" | "expboost" }} tier4
 * @property {{ type: "multiplier" | "expboost" }} tier5
 * @property {{ type: "multiplier" | "expboost" }} tier6
 * @property {{ type: "multiplier" | "expboost" }} tier7
 * @property {{ type: "multiplier" | "expboost" }} tier8
 * @property {{ type: "multiplier" | "expboost" }} tier9
 * @property {{ type: "multiplier" | "expboost" }} tier10
 * @property {{ type: "multiplier" | "expboost" }} tier11
 * @property {{ type: "multiplier" | "expboost" }} tier12
 * @property {{ type: "multiplier" | "expboost" }} tier13
 * @property {{ type: "multiplier" | "expboost" }} tier14
 * @property {{ type: "multiplier" | "expboost" }} tier15
 * @property {{ type: "multiplier" | "expboost" }} tier16
 * @property {{ type: "multiplier" | "expboost" }} tier17
 * @property {{ type: "multiplier" | "expboost" }} tier18
 * @property {{ type: "multiplier" | "expboost" }} tier19
 * @property {{ type: "multiplier" | "expboost" }} tier20
 * @property {{ type: "multiplier" | "expboost" }} tier21
 * @property {{ type: "multiplier" | "expboost" }} tier22
 * @property {{ type: "multiplier" | "expboost" }} tier23
 * @property {{ type: "multiplier" | "expboost" }} tier24
 * @property {{ type: "multiplier" | "expboost" }} tier25
 * @property {{ type: "multiplier" | "expboost" }} tier26
 * @property {{ type: "multiplier" | "expboost" }} tier27
 * @property {{ type: "multiplier" | "expboost" }} tier28
 * @property {{ type: "multiplier" | "expboost" }} tier29
 * @property {{ type: "multiplier" | "expboost" }} tier30
 * @property {{ type: "multiplier" | "expboost" }} tier31
 * @property {{ type: "multiplier" | "expboost" }} tier32
 * @property {{ type: "multiplier" | "expboost" }} tier33
 * @property {{ type: "multiplier" | "expboost" }} tier34
 * @property {{ type: "multiplier" | "expboost" }} tier35
 * @property {{ type: "multiplier" | "expboost" }} tier36
 * @property {{ type: "multiplier" | "expboost" }} tier37
 * @property {{ type: "multiplier" | "expboost" }} tier38
 * @property {{ type: "multiplier" | "expboost" }} tier39
 * @property {{ type: "multiplier" | "expboost" }} tier40
 * @property {{ type: "multiplier" | "expboost" }} tier41
 * @property {{ type: "multiplier" | "expboost" }} tier42
 * @property {{ type: "multiplier" | "expboost" }} tier43
 * @property {{ type: "multiplier" | "expboost" }} tier44
 * @property {{ type: "multiplier" | "expboost" }} tier45
 * @property {{ type: "multiplier" | "expboost" }} tier46
 * @property {{ type: "multiplier" | "expboost" }} tier47
 * @property {{ type: "multiplier" | "expboost" }} tier48
 * @property {{ type: "multiplier" | "expboost" }} tier49
 * @property {{ type: "multiplier" | "expboost" }} tier50
 * @property {{ type: "multiplier" | "expboost" }} tier51
 * @property {{ type: "multiplier" | "expboost" }} tier52
 * @property {{ type: "multiplier" | "expboost" }} tier53
 * @property {{ type: "multiplier" | "expboost" }} tier54
 * @property {{ type: "multiplier" | "expboost" }} tier55
 * @property {{ type: "multiplier" | "expboost" }} tier56
 * @property {{ type: "multiplier" | "expboost" }} tier57
 * @property {{ type: "multiplier" | "expboost" }} tier58
 * @property {{ type: "multiplier" | "expboost" }} tier59
 * @property {{ type: "multiplier" | "expboost" }} tier60
 * @property {{ type: "multiplier" | "expboost" }} tier61
 * @property {{ type: "multiplier" | "expboost" }} tier62
 * @property {{ type: "multiplier" | "expboost" }} tier63
 * @property {{ type: "multiplier" | "expboost" }} tier64
 * @property {{ type: "multiplier" | "expboost" }} tier65
 * @property {{ type: "multiplier" | "expboost" }} tier66
 * @property {{ type: "multiplier" | "expboost" }} tier67
 * @property {{ type: "multiplier" | "expboost" }} tier68
 * @property {{ type: "multiplier" | "expboost" }} tier69
 * @property {{ type: "multiplier" | "expboost" }} tier70
 * @property {{ type: "multiplier" | "expboost" }} tier71
 * @property {{ type: "multiplier" | "expboost" }} tier72
 * @property {{ type: "multiplier" | "expboost" }} tier73
 * @property {{ type: "multiplier" | "expboost" }} tier74
 * @property {{ type: "multiplier" | "expboost" }} tier75
 * @property {{ type: "multiplier" | "expboost" }} tier76
 * @property {{ type: "multiplier" | "expboost" }} tier77
 * @property {{ type: "multiplier" | "expboost" }} tier78
 * @property {{ type: "multiplier" | "expboost" }} tier79
 * @property {{ type: "multiplier" | "expboost" }} tier80
 * @property {{ type: "multiplier" | "expboost" }} tier81
 * @property {{ type: "multiplier" | "expboost" }} tier82
 * @property {{ type: "multiplier" | "expboost" }} tier83
 * @property {{ type: "multiplier" | "expboost" }} tier84
 * @property {{ type: "multiplier" | "expboost" }} tier85
 * @property {{ type: "multiplier" | "expboost" }} tier86
 * @property {{ type: "multiplier" | "expboost" }} tier87
 * @property {{ type: "multiplier" | "expboost" }} tier88
 * @property {{ type: "multiplier" | "expboost" }} tier89
 * @property {{ type: "multiplier" | "expboost" }} tier90
 * @property {{ type: "multiplier" | "expboost" }} tier91
 * @property {{ type: "multiplier" | "expboost" }} tier92
 * @property {{ type: "multiplier" | "expboost" }} tier93
 * @property {{ type: "multiplier" | "expboost" }} tier94
 * @property {{ type: "multiplier" | "expboost" }} tier95
 * @property {{ type: "multiplier" | "expboost" }} tier96
 * @property {{ type: "multiplier" | "expboost" }} tier97
 * @property {{ type: "multiplier" | "expboost" }} tier98
 * @property {{ type: "multiplier" | "expboost" }} tier99
 * @property {{ type: "multiplier" | "expboost" }} tier100
 */

/**
 * @typedef SingleSeason
 * @property {Tiers} normal
 * @property {Tiers} premium
 */
